name: Blassedclans
version: ${project.version}
main: io.github.nircuito.blassedclans.BlassedClans
api-version: 1.8
authors: [ Blassed ]
description: Plugin de clanes
commands:
  clanes:
    description: hola

